import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafa",
  },
  content: {
    padding: 24,
    paddingBottom: 48,
  },
  centered: {
    justifyContent: "center",
    alignItems: "center",
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#111827",
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 14,
    color: "#6e7a75",
    textAlign: "center",
    marginTop: 8,
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#117864",
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 24,
    width: "100%",
    marginTop: 16,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "bold",
  },
  outlineButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1.5,
    borderColor: "#117864",
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 24,
    width: "100%",
    marginTop: 12,
    backgroundColor: "transparent",
  },
  outlineButtonText: {
    color: "#117864",
    fontSize: 15,
    fontWeight: "bold",
  },
  scoreCard: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#e0e6e6",
    shadowColor: "#117864",
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 3,
  },
  scoreLabel: {
    fontSize: 13,
    color: "#6e7a75",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  scoreBig: {
    fontSize: 42,
    fontWeight: "900",
    color: "#117864",
  },
  scorePercent: {
    fontSize: 16,
    fontWeight: "700",
    color: "#6e7a75",
  },
  historySection: {
    width: "100%",
    gap: 10,
    marginTop: 16,
  },
  historySectionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  historySectionTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#111827",
  },
  historyViewAll: {
    fontSize: 13,
    color: "#117864",
    fontWeight: "600",
  },
  historyRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e0e6e6",
    borderRadius: 16,
    padding: 16,
  },
  historyDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 10,
  },
  historyAttemptLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
    flex: 1,
  },
  historyScore: {
    fontSize: 14,
    fontWeight: "700",
  },
  titleContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
});
