import { StyleSheet } from "react-native";
import { theme } from "@/theme/themes";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    padding: 24,
    paddingBottom: 48,
  },
  centered: {
    justifyContent: "center",
    alignItems: "center",
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: theme.colors.textHeading,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    textAlign: "center",
    marginTop: 8,
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.primary,
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 24,
    width: "100%",
    marginTop: 16,
  },
  primaryButtonText: {
    color: theme.colors.textLight,
    fontSize: 15,
    fontWeight: "bold",
  },
  outlineButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1.5,
    borderColor: theme.colors.primary,
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 24,
    width: "100%",
    marginTop: 12,
    backgroundColor: "transparent",
  },
  outlineButtonText: {
    color: theme.colors.primary,
    fontSize: 15,
    fontWeight: "bold",
  },
  scoreCard: {
    width: "100%",
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: theme.colors.border,
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 3,
  },
  scoreLabel: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  scoreBig: {
    fontSize: 42,
    fontWeight: "900",
    color: theme.colors.primary,
  },
  scorePercent: {
    fontSize: 16,
    fontWeight: "700",
    color: theme.colors.textSecondary,
  },
  historySection: {
    width: "100%",
    gap: 10,
    marginTop: 16,
  },
  historySectionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  historySectionTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: theme.colors.textHeading,
  },
  historyViewAll: {
    fontSize: 13,
    color: theme.colors.primary,
    fontWeight: "600",
  },
  historyRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 16,
    padding: 16,
  },
  historyDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 10,
  },
  historyAttemptLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.text,
    flex: 1,
  },
  historyScore: {
    fontSize: 14,
    fontWeight: "700",
  },
  titleContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
});
