import { theme } from "@/theme/themes";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: theme.colors.background,
    borderBottomWidth: 1,
    borderColor: theme.colors.borderMuted,
  },
  headerButton: {
    padding: 8,
    borderRadius: 9999,
  },
  headerTitleContainer: {
    flex: 1,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  headerTitleText: {
    fontWeight: "bold",
    fontSize: 16,
    color: theme.colors.textHeading,
    textAlign: "center",
  },
  headerSubtitleText: {
    fontSize: 10,
    color: theme.colors.primary,
    fontWeight: "600",
    marginTop: 2,
  },
  chatWrapper: {
    flex: 1,
    backgroundColor: theme.colors.gray50,
  },
  chatScroll: {
    flex: 1,
    padding: 16,
  },
  inputPanel: {
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: "transparent",
    borderTopWidth: 0,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 9999,
    paddingVertical: 4,
    paddingLeft: 8,
    paddingRight: 6,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  inputAddButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
  },
  textInput: {
    flex: 1,
    paddingHorizontal: 12,
    fontSize: 14,
    color: theme.colors.textHeading,
  },
  inputMicButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
  },
  inputSendButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    elevation: 1,
    backgroundColor: theme.colors.primary,
  },
  inputSendButtonPressed: {
    transform: [{ scale: 0.93 }],
  },
  citationSheetContent: {
    marginTop: 4,
  },
  citationMetaCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
    backgroundColor: theme.colors.gray50,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
  },
  citationMetaTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: theme.colors.text,
  },
  citationMetaSubtitle: {
    fontSize: 10,
    color: theme.colors.textMuted,
    marginTop: 2,
  },
  citationContextCard: {
    padding: 16,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    borderRadius: 12,
  },
  citationContextText: {
    fontSize: 12,
    lineHeight: 18,
    color: theme.colors.gray700,
  },
  highlightText: {
    backgroundColor: theme.colors.highlightBg,
    color: theme.colors.highlightText,
    fontWeight: "600",
    borderRadius: 4,
    paddingHorizontal: 2,
  },
  citationActionsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  citationPrimaryButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: theme.colors.primary,
  },
  citationPrimaryButtonPressed: {
    backgroundColor: theme.colors.primaryDark,
  },
  citationPrimaryButtonText: {
    fontSize: 12,
    fontWeight: "bold",
    color: theme.colors.textLight,
  },
  citationSecondaryButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: theme.colors.gray100,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
  },
  citationSecondaryButtonText: {
    fontSize: 12,
    fontWeight: "bold",
    color: theme.colors.gray500,
  },
  menuSheetContent: {
    paddingBottom: 24,
    gap: 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 16,
    gap: 16,
  },
  menuItemPressed: {
    backgroundColor: theme.colors.gray100,
  },
  menuIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  menuIconSources: {
    backgroundColor: "rgba(17, 120, 100, 0.1)",
  },
  menuIconStudio: {
    backgroundColor: "rgba(218, 247, 166, 0.3)",
  },
  menuIconInvite: {
    backgroundColor: theme.colors.gray100,
  },
  menuTextContainer: {
    flex: 1,
  },
  menuItemTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: theme.colors.text,
  },
  menuItemSubtitle: {
    fontSize: 11,
    color: theme.colors.textMuted,
    marginTop: 2,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  emptyStateHeader: {
    alignItems: "center",
    marginBottom: 32,
  },
  emptyStateTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: theme.colors.textHeading,
    textAlign: "center",
    marginTop: 16,
  },
  emptyStateSubtitle: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    textAlign: "center",
    marginTop: 8,
    lineHeight: 20,
  },
  suggestionsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    width: "100%",
    rowGap: 12,
  },
  suggestionCard: {
    width: "48%",
    flexDirection: "column",
    alignItems: "flex-start",
    borderRadius: 16,
    padding: 14,
    minHeight: 110,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  suggestionCardPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.96 }],
  },
  suggestionCardIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  suggestionCardText: {
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 16,
    color: theme.colors.text,
  },
});
