import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafa",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: "#f8fafa",
    borderBottomWidth: 1,
    borderColor: "#e5e7eb",
  },
  headerButton: {
    padding: 8,
    borderRadius: 9999,
  },
  headerTitleContainer: {
    flex: 1,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  headerTitleText: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#111827",
    textAlign: "center",
  },
  headerSubtitleText: {
    fontSize: 10,
    color: "#117864",
    fontWeight: "600",
    marginTop: 2,
  },
  chatWrapper: {
    flex: 1,
    backgroundColor: "#f9fafb",
  },
  chatScroll: {
    flex: 1,
    padding: 16,
  },
  inputPanel: {
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: "transparent",
    borderTopWidth: 0,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e0e6e6",
    borderRadius: 9999,
    paddingVertical: 4,
    paddingLeft: 8,
    paddingRight: 6,
    shadowColor: "#117864",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  inputAddButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
  },
  textInput: {
    flex: 1,
    paddingHorizontal: 12,
    fontSize: 14,
    color: "#111827",
  },
  inputMicButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
  },
  inputSendButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    elevation: 1,
    backgroundColor: "#117864",
  },
  inputSendButtonPressed: {
    transform: [{ scale: 0.93 }],
  },
  citationSheetContent: {
    marginTop: 4,
  },
  citationMetaCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
    backgroundColor: "#f9fafb",
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  citationMetaTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#1f2937",
  },
  citationMetaSubtitle: {
    fontSize: 10,
    color: "#9ca3af",
    marginTop: 2,
  },
  citationContextCard: {
    padding: 16,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
  },
  citationContextText: {
    fontSize: 12,
    lineHeight: 18,
    color: "#374151",
  },
  highlightText: {
    backgroundColor: "rgba(218, 247, 166, 0.4)",
    color: "#131f00",
    fontWeight: "600",
    borderRadius: 4,
    paddingHorizontal: 2,
  },
  citationActionsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  citationPrimaryButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#117864",
  },
  citationPrimaryButtonPressed: {
    backgroundColor: "#005d4d",
  },
  citationPrimaryButtonText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#ffffff",
  },
  citationSecondaryButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: "#f3f4f6",
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  citationSecondaryButtonText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#4b5563",
  },
  menuSheetContent: {
    paddingBottom: 24,
    gap: 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 16,
    gap: 16,
  },
  menuItemPressed: {
    backgroundColor: "#f3f4f6",
  },
  menuIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  menuIconSources: {
    backgroundColor: "rgba(17, 120, 100, 0.1)",
  },
  menuIconStudio: {
    backgroundColor: "rgba(218, 247, 166, 0.3)",
  },
  menuIconInvite: {
    backgroundColor: "#f3f4f6",
  },
  menuTextContainer: {
    flex: 1,
  },
  menuItemTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1f2937",
  },
  menuItemSubtitle: {
    fontSize: 11,
    color: "#9ca3af",
    marginTop: 2,
  },
});
