import { StyleSheet } from "react-native";
import { theme } from "@/theme/themes";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    padding: 24,
    paddingBottom: 48,
    gap: 16,
  },
  scoreCard: {
    width: "100%",
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: theme.colors.border,
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 3,
    marginBottom: 8,
  },
  emojiText: {
    fontSize: 40,
    textAlign: "center",
  },
  gradeText: {
    fontSize: 18,
    fontWeight: "bold",
    color: theme.colors.textHeading,
  },
  scoreBig: {
    fontSize: 42,
    fontWeight: "900",
    color: theme.colors.primary,
  },
  scorePercent: {
    fontSize: 16,
    fontWeight: "700",
    color: theme.colors.textSecondary,
  },
  resultBarTrack: {
    width: "100%",
    height: 8,
    backgroundColor: theme.colors.border,
    borderRadius: 4,
    marginTop: 8,
  },
  resultBarFill: {
    height: 8,
    borderRadius: 4,
  },
  historySectionTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: theme.colors.textHeading,
  },
  breakdownCard: {
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    marginBottom: 12,
  },
  correctCard: {
    backgroundColor: theme.colors.successLight,
    borderColor: theme.colors.accentGreen,
  },
  incorrectCard: {
    backgroundColor: theme.colors.errorLight,
    borderColor: theme.colors.accentRed,
  },
  breakdownHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  breakdownQ: {
    fontSize: 14,
    fontWeight: "700",
  },
  breakdownQuestion: {
    fontSize: 15,
    fontWeight: "600",
    color: theme.colors.text,
    marginBottom: 8,
  },
  breakdownYour: {
    fontSize: 13,
    color: theme.colors.gray500,
    marginBottom: 4,
  },
  breakdownYourText: {
    fontWeight: "700",
  },
  breakdownCorrect: {
    fontSize: 13,
    color: theme.colors.primary,
    marginBottom: 4,
  },
  breakdownExplanation: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    lineHeight: 18,
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(224, 230, 230, 0.5)",
    paddingTop: 8,
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.primary,
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 24,
    width: "100%",
    marginTop: 8,
  },
  primaryButtonText: {
    color: theme.colors.textLight,
    fontSize: 15,
    fontWeight: "bold",
  },
  outlineButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1.5,
    borderColor: theme.colors.primary,
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 24,
    width: "100%",
    marginTop: 12,
    backgroundColor: "transparent",
  },
  outlineButtonText: {
    color: theme.colors.primary,
    fontSize: 15,
    fontWeight: "bold",
  },
});
