import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafa",
  },
  content: {
    padding: 24,
    paddingBottom: 48,
    gap: 16,
  },
  scoreCard: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#e0e6e6",
    shadowColor: "#117864",
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 3,
    marginBottom: 8,
  },
  emojiText: {
    fontSize: 40,
    textAlign: "center",
  },
  gradeText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111827",
  },
  scoreBig: {
    fontSize: 42,
    fontWeight: "900",
    color: "#117864",
  },
  scorePercent: {
    fontSize: 16,
    fontWeight: "700",
    color: "#6e7a75",
  },
  resultBarTrack: {
    width: "100%",
    height: 8,
    backgroundColor: "#e0e6e6",
    borderRadius: 4,
    marginTop: 8,
  },
  resultBarFill: {
    height: 8,
    borderRadius: 4,
  },
  historySectionTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#111827",
  },
  breakdownCard: {
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e0e6e6",
    backgroundColor: "#fff",
    marginBottom: 12,
  },
  correctCard: {
    backgroundColor: "#e8f5e9",
    borderColor: "#2e7d32",
  },
  incorrectCard: {
    backgroundColor: "#ffebee",
    borderColor: "#c62828",
  },
  breakdownHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  breakdownQ: {
    fontSize: 14,
    fontWeight: "700",
  },
  breakdownQuestion: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1f2937",
    marginBottom: 8,
  },
  breakdownYour: {
    fontSize: 13,
    color: "#4b5563",
    marginBottom: 4,
  },
  breakdownYourText: {
    fontWeight: "700",
  },
  breakdownCorrect: {
    fontSize: 13,
    color: "#117864",
    marginBottom: 4,
  },
  breakdownExplanation: {
    fontSize: 13,
    color: "#6b7280",
    lineHeight: 18,
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(224, 230, 230, 0.5)",
    paddingTop: 8,
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#117864",
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 24,
    width: "100%",
    marginTop: 8,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "bold",
  },
  outlineButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1.5,
    borderColor: "#117864",
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 24,
    width: "100%",
    marginTop: 12,
    backgroundColor: "transparent",
  },
  outlineButtonText: {
    color: "#117864",
    fontSize: 15,
    fontWeight: "bold",
  },
});
