import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafa",
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  loadingText: {
    marginTop: 12,
    color: "#6e7a75",
    fontSize: 14,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: "#e0e6e6",
  },
  headerButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#117864",
    flex: 1,
    textAlign: "center",
  },
  headerPlaceholder: {
    width: 40,
  },
  scrollView: {
    flex: 1,
    padding: 20,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: "#6e7a75",
    marginBottom: 24,
    lineHeight: 20,
  },
  timeline: {
    paddingLeft: 8,
  },
  timelineStep: {
    flexDirection: "row",
    marginBottom: 24,
  },
  markerContainer: {
    alignItems: "center",
    marginRight: 16,
  },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#e8f5f3",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    borderWidth: 1,
    borderColor: "#a2d9ce",
  },
  connectorLine: {
    width: 2,
    flex: 1,
    backgroundColor: "#a2d9ce",
    position: "absolute",
    top: 36,
    bottom: -24,
    zIndex: 1,
  },
  card: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e0e6e6",
    borderRadius: 16,
    padding: 16,
    shadowColor: "#117864",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
    gap: 8,
  },
  stepTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
  },
  stepDesc: {
    fontSize: 13,
    color: "#4b5563",
    lineHeight: 18,
  },
  reasonBox: {
    flexDirection: "row",
    gap: 6,
    backgroundColor: "#f2f4f4",
    borderRadius: 8,
    padding: 10,
    marginTop: 4,
  },
  reasonText: {
    flex: 1,
    fontSize: 12,
    color: "#5d6d7e",
    lineHeight: 16,
  },
  sourceTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#e8f5f3",
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  sourceTagPressed: {
    opacity: 0.7,
  },
  sourceTagText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#117864",
  },
  generatingTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
    marginTop: 20,
  },
  generatingSubtitle: {
    fontSize: 13,
    color: "#6e7a75",
    textAlign: "center",
    marginTop: 8,
    lineHeight: 18,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#111827",
    marginTop: 16,
  },
  emptySubtitle: {
    fontSize: 14,
    color: "#6e7a75",
    textAlign: "center",
    marginTop: 8,
    marginBottom: 24,
    lineHeight: 20,
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#117864",
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 16,
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 15,
  },
  sheetContent: {
    paddingVertical: 4,
  },
  metaCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
    backgroundColor: "#f9fafb",
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  metaTextContainer: {
    flex: 1,
  },
  metaTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#1f2937",
  },
  metaSubtitle: {
    fontSize: 11,
    color: "#6b7280",
    marginTop: 2,
  },
  detailSection: {
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  detailLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: "#6e7a75",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  detailVal: {
    fontSize: 14,
    color: "#374151",
    lineHeight: 20,
  },
  detailConceptBold: {
    fontWeight: "700",
  },
  detailValLink: {
    color: "#117864",
    textDecorationLine: "underline",
  },
  sheetDoneButton: {
    marginTop: 20,
  },
  pressedOpacity: {
    opacity: 0.9,
  },
});
