import { StyleSheet } from "react-native";
import { theme } from "@/theme/themes";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  loadingText: {
    marginTop: 12,
    color: theme.colors.textSecondary,
    fontSize: 14,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: theme.colors.border,
  },
  headerButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: theme.colors.primary,
    flex: 1,
    textAlign: "center",
  },
  headerPlaceholder: {
    width: 40,
  },
  scrollView: {
    flex: 1,
    padding: 20,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: theme.colors.textHeading,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    marginBottom: 24,
    lineHeight: 20,
  },
  timeline: {
    paddingLeft: 8,
  },
  timelineStep: {
    flexDirection: "row",
    marginBottom: 24,
  },
  markerContainer: {
    alignItems: "center",
    marginRight: 16,
  },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.primarySubtle,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    borderWidth: 1,
    borderColor: theme.colors.primaryLight,
  },
  connectorLine: {
    width: 2,
    flex: 1,
    backgroundColor: theme.colors.primaryLight,
    position: "absolute",
    top: 36,
    bottom: -24,
    zIndex: 1,
  },
  card: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 16,
    padding: 16,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
    gap: 8,
  },
  stepTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: theme.colors.textHeading,
  },
  stepDesc: {
    fontSize: 13,
    color: theme.colors.gray700,
    lineHeight: 18,
  },
  reasonBox: {
    flexDirection: "row",
    gap: 6,
    backgroundColor: theme.colors.gray50,
    borderRadius: 8,
    padding: 10,
    marginTop: 4,
  },
  reasonText: {
    flex: 1,
    fontSize: 12,
    color: theme.colors.grayTextMedium,
    lineHeight: 16,
  },
  sourceTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: theme.colors.primarySubtle,
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  sourceTagPressed: {
    opacity: 0.7,
  },
  sourceTagText: {
    fontSize: 11,
    fontWeight: "600",
    color: theme.colors.primary,
  },
  generatingTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.colors.textHeading,
    marginTop: 20,
  },
  generatingSubtitle: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    textAlign: "center",
    marginTop: 8,
    lineHeight: 18,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: theme.colors.textHeading,
    marginTop: 16,
  },
  emptySubtitle: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    textAlign: "center",
    marginTop: 8,
    marginBottom: 24,
    lineHeight: 20,
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: theme.colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 16,
  },
  primaryButtonText: {
    color: theme.colors.textLight,
    fontWeight: "bold",
    fontSize: 15,
  },
  sheetContent: {
    paddingVertical: 4,
  },
  metaCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
    backgroundColor: theme.colors.gray50,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
  },
  metaTextContainer: {
    flex: 1,
  },
  metaTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: theme.colors.text,
  },
  metaSubtitle: {
    fontSize: 11,
    color: theme.colors.gray500,
    marginTop: 2,
  },
  detailSection: {
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  detailLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: theme.colors.textSecondary,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  detailVal: {
    fontSize: 14,
    color: theme.colors.gray700,
    lineHeight: 20,
  },
  detailConceptBold: {
    fontWeight: "700",
  },
  detailValLink: {
    color: theme.colors.primary,
    textDecorationLine: "underline",
  },
  sheetDoneButton: {
    marginTop: 20,
  },
  pressedOpacity: {
    opacity: 0.9,
  },
});
