import { StyleSheet } from "react-native";

export const getStyles = (insets: { top: number; bottom: number }) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#f8fafa",
      paddingTop: insets.top,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 12,
      backgroundColor: "#f8fafa",
    },
    profileContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    profileImage: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: "#e0e6e6",
    },
    workspaceText: {
      fontSize: 20,
      fontWeight: "600",
      color: "#117864",
    },
    workspaceSelector: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      marginTop: 2,
    },
    workspaceType: {
      fontSize: 12,
      color: "#6e7a75",
    },
    headerSearchButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    scrollView: {
      flex: 1,
      paddingHorizontal: 20,
    },
    scrollViewContent: {
      paddingBottom: 150,
    },
    searchBar: {
      marginVertical: 16,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#ffffff",
      borderWidth: 1,
      borderColor: "#e0e6e6",
      borderRadius: 24,
      paddingHorizontal: 12,
      paddingVertical: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    searchIcon: {
      marginRight: 8,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: "#1f2937",
    },
    micButton: {
      padding: 4,
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#111827",
    },
    filterButton: {
      padding: 4,
      borderRadius: 9999,
    },
    grid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
    notebookCard: {
      width: "48%",
      backgroundColor: "#ffffff",
      borderWidth: 1,
      borderColor: "#e0e6e6",
      borderRadius: 24,
      padding: 16,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    notebookCardPressed: {
      transform: [{ scale: 0.96 }],
    },
    notebookIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 12,
    },
    notebookTitle: {
      fontSize: 14,
      fontWeight: "600",
      color: "#030712",
      lineHeight: 20,
      marginBottom: 8,
      height: 40,
    },
    notebookMeta: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: "auto",
    },
    notebookMetaText: {
      fontSize: 12,
      color: "#6e7a75",
      marginLeft: 4,
    },
    addNotebookCard: {
      width: "48%",
      backgroundColor: "#f8fafa",
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: "#e0e6e6",
      borderRadius: 24,
      padding: 16,
      marginBottom: 16,
      alignItems: "center",
      justifyContent: "center",
      height: 142,
    },
    addNotebookCardPressed: {
      transform: [{ scale: 0.96 }],
      opacity: 0.85,
    },
    addNotebookIconContainer: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: "#f3f4f6",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 8,
    },
    addNotebookText: {
      fontSize: 12,
      fontWeight: "600",
      color: "#9ca3af",
    },
    drawerItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
      padding: 12,
      borderRadius: 24,
    },
    drawerItemPressed: {
      backgroundColor: "#f9fafb",
    },
    drawerItemIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "#f3f4f6",
      alignItems: "center",
      justifyContent: "center",
    },
    drawerItemIconContainerPrimary: {
      backgroundColor: "rgba(162, 217, 206, 0.35)",
    },
    drawerItemText: {
      fontSize: 14,
      fontWeight: "600",
      color: "#1f2937",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.4)",
      justifyContent: "center",
      alignItems: "center",
      padding: 24,
    },
    modalContent: {
      width: "100%",
      maxWidth: 340,
      backgroundColor: "#ffffff",
      borderRadius: 20,
      padding: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#111827",
      marginBottom: 8,
    },
    modalSubtitle: {
      fontSize: 14,
      color: "#4b5563",
      marginBottom: 16,
    },
    modalInput: {
      width: "100%",
      height: 48,
      borderWidth: 1,
      borderColor: "#e5e7eb",
      borderRadius: 12,
      paddingHorizontal: 16,
      fontSize: 15,
      color: "#111827",
      marginBottom: 20,
    },
    modalButtons: {
      flexDirection: "row",
      gap: 12,
      justifyContent: "flex-end",
    },
    modalButton: {
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    modalCancelButton: {
      backgroundColor: "#f3f4f6",
      borderWidth: 1,
      borderColor: "#e5e7eb",
    },
    modalCancelButtonPressed: {
      opacity: 0.8,
    },
    modalCancelButtonText: {
      fontSize: 14,
      fontWeight: "600",
      color: "#4b5563",
    },
    modalCreateButton: {
      backgroundColor: "#117864",
    },
    modalCreateButtonPressed: {
      opacity: 0.8,
    },
    modalCreateButtonText: {
      fontSize: 14,
      fontWeight: "600",
      color: "#ffffff",
    },
  });
