import { theme } from "@/theme/themes";
import { StyleSheet } from "react-native";

export const getStyles = (insets: { top: number; bottom: number }) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
      paddingTop: insets.top,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 14,
      backgroundColor: theme.colors.background,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    profileContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    profileImage: {
      width: 44,
      height: 44,
      borderRadius: 22,
      borderWidth: 1.5,
      borderColor: theme.colors.primary,
    },
    workspaceText: {
      fontSize: 16,
      fontWeight: "700",
      color: theme.colors.textDark,
    },
    workspaceSelector: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      marginTop: 1,
    },
    workspaceType: {
      fontSize: 12,
      color: theme.colors.textSecondary,
      fontWeight: "500",
    },
    headerSearchButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    headerAddButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    headerAddButtonPressed: {
      opacity: 0.7,
    },
    scrollView: {
      flex: 1,
      paddingHorizontal: 20,
    },
    scrollViewContent: {
      paddingBottom: 150,
    },
    searchBar: {
      marginVertical: 16,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 24,
      paddingHorizontal: 12,
      paddingVertical: 10,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    searchIcon: {
      marginRight: 8,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: theme.colors.text,
    },
    micButton: {
      padding: 4,
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: theme.colors.textHeading,
    },
    filterButton: {
      padding: 4,
      borderRadius: 9999,
    },
    grid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
    notebookCard: {
      width: "48%",
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 24,
      padding: 16,
      marginBottom: 16,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    notebookCardPressed: {
      transform: [{ scale: 0.96 }],
    },
    noteBookMetaData: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: "auto",
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: theme.colors.gray100,
    },
    metaItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
    },
    metaText: {
      fontSize: 11,
      color: theme.colors.textSecondary,
      fontWeight: "500",
    },
    notebookIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 12,
    },
    notebookTitle: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.colors.textDark,
      lineHeight: 20,
      marginBottom: 8,
      height: 40,
    },
    addNotebookCard: {
      width: "48%",
      backgroundColor: theme.colors.background,
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: theme.colors.border,
      borderRadius: 24,
      padding: 16,
      marginBottom: 16,
      alignItems: "center",
      justifyContent: "center",
      height: 142,
    },
    addNotebookCardPressed: {
      transform: [{ scale: 0.96 }],
      opacity: 0.85,
    },
    addNotebookIconContainer: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: theme.colors.gray100,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 8,
    },
    addNotebookText: {
      fontSize: 12,
      fontWeight: "600",
      color: theme.colors.textMuted,
    },
    drawerItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
      padding: 12,
      borderRadius: 24,
    },
    drawerItemPressed: {
      backgroundColor: theme.colors.gray50,
    },
    drawerItemIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.colors.gray100,
      alignItems: "center",
      justifyContent: "center",
    },
    drawerItemIconContainerPrimary: {
      backgroundColor: theme.colors.primarySubtle,
    },
    drawerItemText: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.colors.text,
    },
    drawerItemDisabled: {
      opacity: 0.6,
    },
    badgeContainer: {
      marginLeft: "auto",
      backgroundColor: theme.colors.gray100,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    badgeText: {
      fontSize: 10,
      fontWeight: "600",
      color: theme.colors.textSecondary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.4)",
      justifyContent: "center",
      alignItems: "center",
      padding: 24,
    },
    modalContent: {
      width: "100%",
      maxWidth: 340,
      backgroundColor: theme.colors.surface,
      borderRadius: 20,
      padding: 24,
      shadowColor: theme.colors.black,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: theme.colors.textHeading,
      marginBottom: 8,
    },
    modalSubtitle: {
      fontSize: 14,
      color: theme.colors.gray500,
      marginBottom: 16,
    },
    modalInput: {
      width: "100%",
      height: 48,
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
      borderRadius: 12,
      paddingHorizontal: 16,
      fontSize: 15,
      color: theme.colors.textHeading,
      marginBottom: 20,
    },
    modalButtons: {
      flexDirection: "row",
      gap: 12,
      justifyContent: "flex-end",
    },
    modalButton: {
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    modalCancelButton: {
      backgroundColor: theme.colors.gray100,
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
    },
    modalCancelButtonPressed: {
      opacity: 0.8,
    },
    modalCancelButtonText: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.colors.gray500,
    },
    modalCreateButton: {
      backgroundColor: theme.colors.primary,
    },
    modalCreateButtonPressed: {
      opacity: 0.8,
    },
    modalCreateButtonText: {
      fontSize: 14,
      fontWeight: "600",
      color: theme.colors.textLight,
    },
  });
