import { StyleSheet } from "react-native";
import { theme } from "@/theme/themes";

export const styles = StyleSheet.create({
  sourceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 16,
    paddingVertical: 12,
  },
  sourceButton: {
    width: "48%",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    backgroundColor: theme.colors.gray50,
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    gap: 8,
  },
  sourceIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.colors.primarySubtle,
    alignItems: "center",
    justifyContent: "center",
  },
  sourceButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: theme.colors.text,
    textAlign: "center",
  },
  drawerInput: {
    width: "100%",
    height: 48,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: 16,
    fontSize: 14,
    color: theme.colors.textHeading,
    marginBottom: 16,
    backgroundColor: theme.colors.gray50,
  },
  drawerInputTitle: {
    width: "100%",
    height: 48,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: 16,
    fontSize: 14,
    color: theme.colors.textHeading,
    marginBottom: 12,
    backgroundColor: theme.colors.gray50,
  },
  drawerInputContent: {
    width: "100%",
    height: 160,
    borderWidth: 1,
    borderColor: theme.colors.borderMuted,
    borderRadius: theme.borderRadius.md,
    padding: 16,
    fontSize: 14,
    color: theme.colors.textHeading,
    marginBottom: 16,
    backgroundColor: theme.colors.gray50,
  },
  drawerSubmitButton: {
    width: "100%",
    height: 48,
    backgroundColor: theme.colors.primary,
    borderRadius: theme.borderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  drawerSubmitButtonText: {
    color: theme.colors.textLight,
    fontSize: 14,
    fontWeight: "bold",
  },
});
