import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  sourceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 16,
    paddingVertical: 12,
  },
  sourceButton: {
    width: "48%",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    backgroundColor: "#f9fafb",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    gap: 8,
  },
  sourceIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(162, 217, 206, 0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  sourceButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1f2937",
    textAlign: "center",
  },
  drawerInput: {
    width: "100%",
    height: 48,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 14,
    color: "#111827",
    marginBottom: 16,
    backgroundColor: "#f9fafb",
  },
  drawerInputTitle: {
    width: "100%",
    height: 48,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 14,
    color: "#111827",
    marginBottom: 12,
    backgroundColor: "#f9fafb",
  },
  drawerInputContent: {
    width: "100%",
    height: 160,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    padding: 16,
    fontSize: 14,
    color: "#111827",
    marginBottom: 16,
    backgroundColor: "#f9fafb",
  },
  drawerSubmitButton: {
    width: "100%",
    height: 48,
    backgroundColor: "#117864",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  drawerSubmitButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "bold",
  },
});
